#!/usr/bin/env python3
"""Convert FLARE Tiled .tmx → GDScript map data for Godot.
Usage: python tools/convert_tmx_to_gd.py input.tmx output.gd [source_name]
"""

import xml.etree.ElementTree as ET
import sys
import os
import re


def parse_tmx(xml_text):
    root = ET.fromstring(xml_text)
    width = int(root.get("width"))
    height = int(root.get("height"))

    # Parse tilesets
    tilesets = []
    for ts in root.findall("tileset"):
        firstgid = int(ts.get("firstgid"))
        name = ts.get("name")
        tw = int(ts.get("tilewidth"))
        th = int(ts.get("tileheight"))
        tilecount = int(ts.get("tilecount"))
        columns = int(ts.get("columns"))
        img = ts.find("image")
        img_src = img.get("source") if img is not None else ""
        toff = ts.find("tileoffset")
        ox = int(toff.get("x")) if toff is not None else 0
        oy = int(toff.get("y")) if toff is not None else 0
        tilesets.append({
            "firstgid": firstgid,
            "name": name,
            "tw": tw,
            "th": th,
            "count": tilecount,
            "cols": columns,
            "img": img_src,
            "ox": ox,
            "oy": oy,
        })

    # Parse layers
    layers = {}
    for layer in root.findall("layer"):
        name = layer.get("name")
        data_el = layer.find("data")
        if data_el is None:
            continue
        encoding = data_el.get("encoding", "csv")
        if encoding == "csv":
            text = data_el.text.strip()
            values = [int(v.strip()) for v in text.replace("\n", ",").split(",") if v.strip()]
        else:
            values = []
        # Reshape to 2D
        grid = []
        for y in range(height):
            row = values[y * width : (y + 1) * width]
            grid.append(row)
        layers[name] = grid

    return width, height, tilesets, layers


def gsid_for_gid(gid, tilesets):
    """Find the tileset and local tile index for a GID."""
    if gid == 0:
        return None, None
    for ts in reversed(tilesets):
        if gid >= ts["firstgid"]:
            local_idx = gid - ts["firstgid"]
            return ts, local_idx
    return None, None


def region_rect(local_idx, ts):
    """Calculate the region rect on the source texture."""
    cols = ts["cols"]
    col = local_idx % cols
    row = local_idx // cols
    # The region rect uses the actual pixel tile size
    # For tilesheets where Tiled's tileheight differs from pixel tile size,
    # we use the smaller of (actual image row height) and Tiled's tileheight
    return col, row


def generate_gd(width, height, tilesets, layers, source_name="map.tmx"):
    """Generate GDScript map data."""
    bg = layers.get("background", [])
    obj = layers.get("object", [])
    col_layer = layers.get("collision", [])

    lines = []
    lines.append("# Generated by convert_tmx_to_gd.py")
    lines.append("# Source: FLARE Empyrean Campaign - %s" % source_name)
    lines.append("static func get_data() -> Dictionary:")
    lines.append("    return {")
    lines.append('        "width": %d,' % width)
    lines.append('        "height": %d,' % height)

    # Background layer
    lines.append('        "background": [')
    for y in range(height):
        row = bg[y] if y < len(bg) else [0] * width
        row_str = ",".join(str(v) for v in row)
        comma = "," if y < height - 1 else ""
        lines.append("            [%s]%s" % (row_str, comma))
    lines.append("        ],")

    # Object layer
    lines.append('        "object": [')
    for y in range(height):
        row = obj[y] if y < len(obj) else [0] * width
        row_str = ",".join(str(v) for v in row)
        comma = "," if y < height - 1 else ""
        lines.append("            [%s]%s" % (row_str, comma))
    lines.append("        ],")

    # Collision layer
    lines.append('        "collision": [')
    for y in range(height):
        row = col_layer[y] if y < len(col_layer) else [0] * width
        row_str = ",".join(str(v) for v in row)
        comma = "," if y < height - 1 else ""
        lines.append("            [%s]%s" % (row_str, comma))
    lines.append("        ]")

    lines.append("    }")

    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) >= 3:
        # File mode: input.tmx output.gd [source_name]
        tmx_path = sys.argv[1]
        out_path = sys.argv[2]
        source_name = sys.argv[3] if len(sys.argv) >= 4 else os.path.basename(tmx_path)
        with open(tmx_path, "r", encoding="utf-8") as f:
            xml_text = f.read()
        width, height, tilesets, layers = parse_tmx(xml_text)
        gd_code = generate_gd(width, height, tilesets, layers, source_name)
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(gd_code)
        print("Wrote %s (%dx%d)" % (out_path, width, height))
    else:
        # Stdin mode (original behavior)
        xml_text = sys.stdin.read()
        width, height, tilesets, layers = parse_tmx(xml_text)
        gd_code = generate_gd(width, height, tilesets, layers)
        sys.stdout.write(gd_code)


if __name__ == "__main__":
    main()
